version: '3.7'

services:
  vault:
    image: vault:1.9.3
    container_name: vault
    restart: always
    volumes:
      - ./data/vault/config:/vault/config
      - ./data/vault/policies:/vault/policies
      - ./data/vault/data:/vault/data
      - ./data/vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    command: vault server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul
    ports:
      - 8200:8200
  consul:
    image: consul:1.9.3
    container_name: consul
    restart: always
    volumes:
      - ./data/consul/config/consul-config.json:/consul/config/config.json
      - ./data/consul/data:/consul/data
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
    command: 'agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/config.json'
